# Generated by Django 2.2.1 on 2019-06-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
